# The configuration for sleeplab-extractor to extract and preprocess a subset
# of signals for automatic sleep staging.
new_dataset_name: "dod_extracted"

# The format of the annotation files.
annotation_format: "json"

# Signals will be extracted to uncompressed numpy arrays.
array_format: "numpy"

# A separate config must be defined for each series to be extracted.
series_configs:

  # Define configs for DOD-H
  - name: "dodh"

    # Exclude recordings with less than one hour of sleep
    filter_conds:
      - name: "tst_less_than_1h"
        method: "sleeplab_format.extractor.preprocess.filter_by_tst"
        kwargs: {"min_tst_sec": 3600.0, "hypnogram_key": "manual_consensus_hypnogram"}

    array_configs:

      # Only the signals specified here will be extracted.
      # The preprocessing of a given signal consists of a list of actions.
      - name: "C3_M2"
        actions:

          # Each action has a freely defined name that is currently not stored anywhere.
          # method is any python function that can be imported from python during the extraction.
          # kwargs defines the arguments that are passed to the method.
          # updated_attributes are key-value pairs that will be changed in the new signal attributes.
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "C3_M2_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"

      - name: "EOG2"
        actions:
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "EOG2_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"

      - name: "EMG"
        actions:
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "EMG_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"

  # Define configs for DOD-O
  - name: "dodo"

    filter_conds:
      - name: "tst_less_than_1h"
        method: "sleeplab_format.extractor.preprocess.filter_by_tst"
        kwargs: {"min_tst_sec": 3600.0, "hypnogram_key": "manual_consensus_hypnogram"}

    array_configs:

      - name: "C3_M2"
        actions:
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "C3_M2_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"

      - name: "EOG2"
        actions:
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "EOG2_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"

      - name: "EMG"
        actions:
          - name: "resample"
            method: "sleeplab_format.extractor.preprocess.resample_polyphase"
            kwargs: {"fs_new": 64}
            updated_attributes: {"sampling_rate": 64, "name": "EMG_64Hz"}

          - name: "highpass"
            method: "sleeplab_format.extractor.preprocess.highpass"
            kwargs: {"cutoff": 0.3}

          - name: "normalize"
            method: "sleeplab_format.extractor.preprocess.z_score_norm"
